name: Keep Render Service Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"

jobs:
  ping-render-service:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping Request
        run: |
          curl -X GET https://chatify-live-chat-server-kuvaka-tech.onrender.com
